### PR TITLE
Add Liang's Thai Food

### PR DESCRIPTION
**Pull request by xvalentino**
Although there is usually a long wait, if you can get past the wait the food is 💣

### CODE REVIEW

**Comment by Ameobea** [comment]
Thai food is :ok_hand: good choice

**Comment by dalexj** [comment]
@xvalentino 
lunch?

**Comment by xvalentino** [comment]
@dalexj yeah

**Comment by dalexj** [comment]
are you in colorado now? I thought you lived in new york

**Comment by xvalentino** [comment]
nope I moved back! I'm living/working downtown near union station. so we should get lunch sometime!

**Comment by dalexj** [comment]
you on slack anywhere?

**Comment by dalexj** [comment]
added you on disc

**Comment by dalexj** [comment]
too hard to get food here as a group. closing

**Pull request closed without merging**
